/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-1",
    "aws_appsync_graphqlEndpoint": "https://jvtjwr2etff5bjfyjmc7lff7ga.appsync-api.us-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-3kttgcyyujgd5dk2jdlg7g4iwi",
    "aws_cognito_identity_pool_id": "us-west-1:ebe78ff2-0909-4e93-a61d-d00232aafa8b",
    "aws_cognito_region": "us-west-1",
    "aws_user_pools_id": "us-west-1_xzTGFH3E3",
    "aws_user_pools_web_client_id": "1navic7h7jpcq66pf2ge9a5ske",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
